# Generated by Django 5.0.1 on 2024-01-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('admn_no', models.CharField(max_length=4)),
                ('branch', models.CharField(max_length=255)),
                ('sem', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='StudentUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_admn_no', models.CharField(max_length=4)),
                ('student_name', models.CharField(max_length=255)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_phone', models.CharField(max_length=10)),
                ('student_password', models.CharField(max_length=255)),
                ('house_name', models.CharField(max_length=255)),
            ],
        ),
    ]
