# Generated by Django 5.0.1 on 2024-01-16 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artfest2024', '0002_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
