# Generated by Django 5.0.1 on 2024-01-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artfest2024', '0004_studentdetails_gender_studentdetails_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_code', models.CharField(max_length=8)),
                ('program_name', models.CharField(max_length=255)),
                ('program_type', models.CharField(choices=[('solo', 'solo')], max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='house',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='studentusers',
            name='program',
            field=models.ManyToManyField(to='artfest2024.programs'),
        ),
    ]
