# Generated by Django 5.0.1 on 2024-01-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artfest2024', '0006_studentusers_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='Gender_choices',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('all', 'All')], default='male', max_length=255),
        ),
        migrations.AlterField(
            model_name='programs',
            name='program_code',
            field=models.CharField(max_length=88),
        ),
    ]
