# Generated by Django 5.0.1 on 2024-01-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artfest2024', '0007_programs_gender_choices_alter_programs_program_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentusers',
            name='Gender',
            field=models.CharField(max_length=20),
        ),
    ]
