# Generated by Django 5.0.1 on 2024-01-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artfest2024', '0008_alter_studentusers_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='Gender_choices',
            field=models.CharField(choices=[('On-Stage', 'On-Stage'), ('Off-Stage', 'Off-Stage')], default='Off-Stage', max_length=255),
        ),
        migrations.AlterField(
            model_name='programs',
            name='program_type',
            field=models.CharField(choices=[('solo', 'solo'), ('Group', 'Group')], max_length=255),
        ),
    ]
