# Generated by Django 5.0.1 on 2024-01-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artfest2024', '0009_alter_programs_gender_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='Stage_choices',
            field=models.CharField(choices=[('On-Stage', 'On-Stage'), ('Off-Stage', 'Off-Stage')], default='Off-Stage', max_length=255),
        ),
        migrations.AlterField(
            model_name='programs',
            name='Gender_choices',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('all', 'All')], default='male', max_length=255),
        ),
    ]
