# Generated by Django 5.0.1 on 2024-01-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artfest2024', '0010_programs_stage_choices_alter_programs_gender_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='programs',
            name='Gender_choices',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('all', 'All')], max_length=255),
        ),
        migrations.AlterField(
            model_name='programs',
            name='Stage_choices',
            field=models.CharField(choices=[('On-Stage', 'On-Stage'), ('Off-Stage', 'Off-Stage')], max_length=255),
        ),
        migrations.AlterField(
            model_name='programs',
            name='program_type',
            field=models.CharField(choices=[('individual', 'individual'), ('Group', 'Group')], max_length=255),
        ),
    ]
