# Generated by Django 5.0.1 on 2024-01-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artfest2024', '0011_contactmessage_alter_programs_gender_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='show_program',
            field=models.BooleanField(default=True),
        ),
    ]
