# Generated by Django 4.2.4 on 2024-02-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artfest2024', '0013_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='max_number_of_people',
            field=models.IntegerField(default=1),
        ),
    ]
