# Generated by Django 5.0.1 on 2024-01-26 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artfest2024', '0013_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(choices=[(1, 'Period 1'), (2, 'Period 2'), (3, 'Period 3'), (4, 'Period 4'), (5, 'Period 5'), (6, 'Period 6')])),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.BooleanField()),
                ('co_ordinator', models.CharField(max_length=255)),
                ('student_admn_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artfest2024.studentusers')),
            ],
        ),
        migrations.CreateModel(
            name='Co_ordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_ordinator_name', models.CharField(max_length=255)),
                ('co_ordinator_email', models.EmailField(max_length=254)),
                ('user_name_for_coordinator', models.CharField(default='', max_length=255)),
                ('password_for_coordinator', models.CharField(default='', max_length=255)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_attendance', to='Attendence.attendance')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artfest2024.programs')),
            ],
        ),
    ]
