# Generated by Django 4.2.4 on 2024-01-28 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='stage',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Attendence.stage'),
        ),
        migrations.AddField(
            model_name='co_ordinator',
            name='stage',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Attendence.stage'),
        ),
    ]
