# Generated by Django 4.2.4 on 2024-01-28 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendence', '0002_stage_attendance_stage_co_ordinator_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='co_ordinator',
            name='attendance',
        ),
    ]
