# Generated by Django 4.2.4 on 2024-01-28 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artfest2024', '0013_notification'),
        ('Attendence', '0003_remove_co_ordinator_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='program',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='artfest2024.programs'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student_admn_no',
            field=models.CharField(max_length=4),
        ),
    ]
