# Generated by Django 4.2.4 on 2024-01-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendence', '0004_attendance_program_alter_attendance_student_admn_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student_admn_no',
            field=models.CharField(default='', max_length=4),
        ),
    ]
