# Generated by Django 4.2.4 on 2024-01-28 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendence', '0005_alter_attendance_student_admn_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
